---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor-registry
  namespace: harbor-registry
spec:
  interval: 30m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: harbor-registry
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    externalURL: https://registry.circlehard.com
    adminPassword: changeme
    persistence:
      persistentVolumeClaim:
        registry:
          size: 50Gi
    core:
      updateStrategy:
        type: Recreate
    jobservice:
      updateStrategy:
        type: Recreate
    registry:
      updateStrategy:
        type: Recreate
    exposureType: ingress
    ingress:
      className: external
      enabled: true
      hosts:
        - host: "registry.${SECRET_DOMAIN}"
      core:
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hostname: "registry.${SECRET_DOMAIN}"
        tls: true
