---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy"
  - path_regex: talosconfig
    encrypted_regex: ^key$
    key_groups:
      - age:
          - "age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy"
  - path_regex: kubeconfig
    encrypted_regex: ^client-key-data$
    key_groups:
      - age:
          - "age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy"
  - path_regex: secrets.yaml
    encrypted_regex: ^(secret|bootstraptoken|secretboxencryptionsecret|token|key)$
    key_groups:
      - age:
          - "age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy"
