apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:TQeM2Kdw3n93Cc/Snf44oexi7IgjPab0tYd87fIFaPk6USpb,iv:8bB+TCwP7iGg5HYZXIpERza44TSpeO5LARPnbtcwHlY=,tag:NQqG1VOJvNE4NaFSMCmb/Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:H7wz6OADpBGwCR0eKihLxLlCuzQdMlB2o0WrYgWA/j1QkrapHZieGQsQNAYwaYSlHun89QihhcSkEGUf4cjT7+zpKrHn05jFB3OVlNulFIlmeURZiYisYU7Zs8IOsZtm2LfUamTKT7W9BW6YBsnRn/MxgOVUm93hYKEcGMTUCMhH7oUFg13+5Nuy7wwGyhiKq5fNb1G0PeHKrP5ALElHNot3WENxSMPpOess+iPtiA==,iv:Edo48+b1HQX1sIgD6c4WUCLaT7JwYEHAKWZ4sL4cEuU=,tag:9kfsqhqgEdv8ICUVgbUhkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UyttcGtDTGpQV1Y3MDdw
            cmMxZ3RMdDJyKzNZVHBGMVdDMHl0QnZxd1FnCnJpU3FESytJSWpqN0lzc3ZCOTBl
            UjdYaFFHUE9NSGNpL0hraE5RYTN0TVEKLS0tIFFCT29wNk9KVHQvb0pOcEtTYStM
            cHpqWkM0dUw2UHRITGFlSGt1b21Gc1EK/6mc3pAqMgMBotyzdHCmXXe3S8VnUo3G
            bmNuKWhQa72N68+zDhpI33hPLmHyc+BnVMUt8t6+zg8LHZaX2oI1hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T16:56:54Z"
    mac: ENC[AES256_GCM,data:oa3CZTnWHtSfddBJcOU8O+uP/3WSJE4rL+6tHs9ek2O5gLtppxS0Sf0IB6Ekmd6Tjifpak5IWjlRjhunQqPURp1UNqWek/WblVioX/+bd5aqDPyMLy3DVwpH5Wdk5W5pFqCj1xdJcsXqWMsP9OQ/4sr0DASTRSSJWf69SHi3a6s=,iv:+HjJV4+PFYV6Bl7Dgy0rR3ejhNLC561wQ4pRwxNU764=,tag:wev3LRpFuDMfjXEwTmJoNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
