apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:AsAlS6k2ri1VPUHOytRApsqagHh0zZhuANy05cKTZUKYpbI+,iv:vnonDSEVgpAiQcP6dM00N/59gZ5ehF5VpQf6CgBhbVg=,tag:fFw0XO1SPRYBP6LkF5OlnA==,type:str]
    credentials.json: ENC[AES256_GCM,data:YKQjiU0+7iX+eCDIBNE30+a1fIPqdaGZH2b6Vdr0C/f2VmQiFIA3pF8lIlPea1S8rxblCMinCdYZnyQ7UOoRZMkUgIXcR8JPIYtfiRhn4pi/qAS44NXZCwLUrskYGmFQttZGZVmHa5YnQBDSo3N4aM+p7E1YHEHi3rXgzzCvRAoBaFo412VBJ5XR40+AP/WNhmr48Qacd2mb+NrckIrZsRS9PhPoEa2X6AHepV7wqg==,iv:Y/Q5muJz8V8DGxRM2zMdtMIlIGFu5+VY/QyN2hi6vwA=,tag:6ZZfNfuPSItbwlOX0+vsJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeUdvUFFySFk0a29NK2xw
            dXFkUWRTZEJPNFlFS1Jla050enQ4bUEzT3lnClh0UlRnU3hKWkhyUWkwL2xSeUFG
            QjcvSXZFWVFuZmF1SjFHdTBrdzRBRFEKLS0tIHNqcXVCRk1FSzN4Y21zYk4ycFd3
            WUYvMVBwYXJha2NZdENmSUJPUU1NNHcKGrRMHukZ9XHUNWRd6JmRrchkRQ79WSWh
            duwVAd91zxgdFMWyG7tgEuqi2WAuDxYBRcfE6qE6dKXhgLX9JHjIgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T22:12:14Z"
    mac: ENC[AES256_GCM,data:/ERWeDTTQwTHe/4P4OeUVATNiD88un1V8P8V0KqNeB2iDI81ZjEpjyVaCqN2AGm1qXYu7KOa1QOX38DOXFvkvT2g9/xQRHeXOldUcDE62ngiF19wC7IAJLE14fAlspUu7ClhvdQVFaOESrbOMzoS5IzAk+2qHXygovjjO2bzWxc=,iv:cHgQGDtjB1tVgPoUbUJtksM8wNTsfs43IBE95YCtqpM=,tag:uvMgoluyrGkMtcwn08lcRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
