apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:COs+go0WO7cFYh1kPNy9RlHFeiB8V7nLCDAk+FS5Hb926mgd,iv:5gMT2hLq7tNKOaihu8JTEagELvz6eQpNXRi2PmguYTI=,tag:KdXWoeFhu2kCc+aRMT4YWQ==,type:str]
    credentials.json: ENC[AES256_GCM,data://3cvSH+7gmjn77JiucQEKBeGez2q2FMvP603NXo1IAZe+GpjsijFe4oi8SkoNMqrQDU8M1mtFTTpfPi/rRZ2umDku2fcXSfD6Fvz6p0WPB8svfrJlklXR8WuYm01GbHD3mA6DXFzR6daFy12EEETH5/7CBAMCT1U6xXJ+040eKhDq62s4C5I9qUWIalD8Zz5p+fYGMGt2qzM+zgzatWd/a2mcenMLiHjUmkAIKUYA==,iv:3QidpepTpk/8jSyo7P1+nbpBN/nPGk9cfW3ybVSgEuM=,tag:TyxWmVVH0MPvXMvwirBZ1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmU0w3QkxKNjZlN3Q2bmI3
            dVNzN3hBRnlWT251d3dCQ2EvNVRKMXRTSTBzClphZGRINW1BL2NyaFdHZEVlTU16
            RmZtTWZ1QTllR09IZzVuTy81bE9YdkUKLS0tIDllV3pEMkdpLzlZUXBGWlJEY3Jj
            bXpBYUhqbTRMVis4aEJOUWkwSVB5NlEKVTMkIznYTz5vC1DsOorxj7W0QCAWk84A
            SD4LfOzi0c16WocjlejJp4Ku4hDTtVLl6Xo86qRe0J1vis/25EOD4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T14:22:35Z"
    mac: ENC[AES256_GCM,data:asp2DuOWXSkGHiKycNmg/R4/s0iWj3OieOvE2AOhDORCg5e7fdLv0lkSB/dJlMg1g19gn/pj5z5dBc68dF4m8ieg3yS5GSUAG+1w9cEDClU6eW1PlSx5FXqjKWto12KmhLD7Wn7BoBZEBmsBtOt2reWhMPWdC9uVB4YT+gnVm0k=,iv:x+ysot7q4H801WGAHQbPM8+Idxr2bqkEr4HnMPLXtIM=,tag:SQBTa855uz+vdEixTGpV2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
