apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:aH/kn5nycbqkjLbwBsmHTOXznDysA/1bHcKC8VCINN2QXz/D,iv:Cahuf4geDmsMdsjTVybcUAxaWSWVnQ1G8qnK1yycGwc=,tag:LXBbX05tAJWANFnOwQD4lA==,type:str]
    credentials.json: ENC[AES256_GCM,data:sfDTIrR1MmNbmLYFyuJGRYph7eJDRYui4jJrndDrMaxsrWXTAs6IuMrMal4xGzHQCf9bfSVegB32OeODE1bSeu/8v7VOMokbomYeTiIkfGHfYSlrwVN0SgYAzy24Velf6jq77p0PJ5ntrvkcbIvUTcz89w4YsNmZ87Oqo59E6vQtLRvDVzsx6ZHyl70bMp3D6Ai8uWqmX0smM51/5smK2yawUfO+nvI+6xxLHO1TfQ==,iv:+zqYZ2rcy0fnHaTfNlDbtHb+ZjIOICGt0tWfG/kc7A0=,tag:tlCRDg5N3tdfM7e0rTUihA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQXRRNElqUmd2am9JQUNR
            NVYrT0ZZbEIwQU5YRXFMNERzYW9mM0ZVTzFFCmdkblppUlZFZG1mUW5jYTNZaTBz
            TGFib1VUeWhzYVB6OFF1amRyZUJDVEUKLS0tIGZGRG5NNzFNT1hTeGM1bmlBMC83
            VVlITCtaZ2x0eHlnWHdWdVlWQ2c4azQK4lOXBnKfJwzygtwWWSyhp+p+UQus4r79
            vBNgEJGMGzXudnjBaO4kGwIFUjt8OwELvH+d64drzoHO1LMGcv+uLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T17:40:58Z"
    mac: ENC[AES256_GCM,data:RDUc8kSdN8obl4Kagqs3swg6AnOipQ2I/Iphan8XWGfNuJzJSXnuC4i8dNiiy+Y8ctPLWyFIsxgOJL0hSnRgGxiwYYX7bz9m4nYJJzpLJjvQiaXOH7D/InApHuVuPl+irwrEmJoTWDEdkgjvGm+ABoYsreGbT1EK79Z7hBnsmVM=,iv:up/GetomyhKjtju+te8nlQZjVH0uxLYemvevGX+lq00=,tag:uNHxwfSLKnvusRv7W5oZsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
