apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:rs2xUGqzlx9VESZ8MTNMvv4q3G1zOk+4gzbQVpo2erTjA846,iv:Ox7KJOyO9sATlNAMmCpNn2pbAahh8FOcx6zB4KRFklw=,tag:KMjTPBjEDdGUyOAh4uQykA==,type:str]
    credentials.json: ENC[AES256_GCM,data:CDSYLHLtkZC5kvnvGgCQnyV2xGJQnDIjRu7T4WUVbhnmajrutFOZdkX4mF+zDcn0Jr2VXUEHkcQd9WPjcgqy7imEQsPtquQC3+GJODSBQQqGiMf2u7ZYh5OM0EZbneXhlyvdtz62hwmuE+E8TkrPfI+byo5yYE0UPWRoOe7u3EVCMT8IRG7RM2nMB+G6ZGjp3bZ1rvQ4TU0mIm544Pdc+BbMA/hNOJ55wMDqmFbrGg==,iv:In1qlQX19sNbdUoou/165vi0qDziyiNVpPab+G0Y784=,tag:/G2ngGzh58HQRRReSXqmFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNN1VIZ241NEdEa0RPWDlp
            cVB1RkZHVGlzRWtVYlE0NEpNVUFYY0Q0TXdrCkxxaTZYajJPdjI5ZEoyR01KQ3Fq
            cHdGekd4cE9LNXdPWVFobEEzemZndUkKLS0tIGZJZkRDYzNub0s1NEhPNC9Bb0hu
            ckg1b292UWdFR2habXlTMGI4anZoUUkKZwq4tbxl5iuEHaDDa0K30XocNNvOF4Br
            bxT/t00Gir6fnqWcY17Xc3ly/eojK6O3jxoJRoDUK+jmj2FAydfOlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T14:39:12Z"
    mac: ENC[AES256_GCM,data:kbWdK0fyXeVyde+wP8+0bD7iA5qtV6cpWbQbwSeM3c3pd8jUGt0bYeNH3V+L2XfMAik/M5KjfQqhxi4Mapq5wEo9JuThYrowugBXMBhsMdxCxqrJJuNTGeerWrTQF7IGfA2anYEWntUJpe+igOVwhgiZd7U08K+F1XyZLpiTE6o=,iv:IHIZmP1Gg7B8FLS2Rg7a1JG9fcv1o/2v/EDO5GfIUFA=,tag:Y/xrRsQDoABVgHNL/3xUvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
