apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Qs8gzXLuDoO/QnkbQWJwQU1/1iG4qpllh/z8Q+l+Ues=,iv:N4CJemyX6ZEC7Sxq26ZgvIq53Q2RaILhkm4fnp5qyi4=,tag:tJZv/ca35PLHvJ8ylkeEFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRnZvNkxtY2NLdDJleThV
            NnVjWTVBWW1odWtGRHIwU1NTNmhQS1VDZ1ZZCjBmaFFzcmpNQzBOZHh4TDVwUlBV
            UlgzOU5henNFcDVOVytXc0hTTnJhV2MKLS0tIDZadUgwSTVpa2JJdUp6WmJXODNJ
            Mi9kaWdKNVowZkpYRld1OXZxbjlxY1kKoZafTTL1pK740qOljcJtPZnBp4EJTeQS
            hUe9wQYnjrctIFL4gujBCswQxpbAlZgOz5vX0EdQ9GgtJtU1bqaKkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T23:20:44Z"
    mac: ENC[AES256_GCM,data:s2M0pSSHpHpMVEsoQJxHlEgtwz1IH9lUCrfMF1p3TT7J+5zGQfDeM+hfXKBX3OSQ+nqzfC7m2+CwXj2kN+jgYpgcI671+eFrePipcgYJX29FLxQP2IHOGHG1Z8qku+JSHf88ZNwu+ORfVv70LuAPoYqmQA1Qg2QqM8XCRCR91XU=,iv:TDZETmLQeGsYiAE67uls339hHaZWEfIDgllYP6Hi+EI=,tag:Dq67+2nq6fccpxl7F+MYeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
