apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:2ST41+Og8eWja2ZdQVv2xzjyMP4LpR3ar9wMKEKzmb0=,iv:9q0ksJz3XiIYIJZYX045Fne5IZI4il0x2rh3ETI8iGw=,tag:Y2YhhW6kdXAXJhaYFs6WWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eEx6bHlIdElZWlU4MTVv
            Z2NXZUY1NFZlVDFnellJN2hseFF2M2NRU2pFCjVoYSsvcWRSbHZTTzBJTkFEWDFS
            aXRtb212Qm9FTldLaUxqSlFwVERPMmcKLS0tIGhuck5lWDI1M2tBbFZ4eFoyb1Ja
            Rm4ybGtXcmxCRVdweXJHSDN5UWxBOE0Kh8UNQcbT0v3lGFFwB4GdRL2CpjiEzeta
            n7KO1PAJZdjXg+AwKp01iRh+W8AXXNqUdzwS2ry1S59A4i1vgUGRKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T14:22:35Z"
    mac: ENC[AES256_GCM,data:5MwICbYJGii07J3dzqov+hWwDL1LI7XiWZJb7s//hZ5cIV5WKE0lNdK+zLRKd5jIiRHtGKG+u0dOUQ6QqYXPVJPwGfl8fIO86Tg81J2y5qI/nICITRD+sKrdgw4odOExJ5SknKd0g4sUs5ptjWt1xZBWcypo3wg0eWaEMObSZ9k=,iv:h0ENa6yJoQv1pD4FsxFr5SsCa8809hqnbAZRDasCLMU=,tag:G6ldYQksewgOnfn7fF7vqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
