apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:gLa1daL4/03Ve4EJkDqnN9krUwBlYbc63Z3BLsbxVfM4UFz0fgX4kQ==,iv:ovYkUkgGrXMgjjiXmycIqqw5fq2zALqIG7cZ3vJDRoc=,tag:LdeaJ8IO3wBpfQysvB5Dcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBME5BR2dZT2lIbk9vL2Ni
            WDRPSXViYnVvbEpVZEtGbGltS0JHdFhtOXk0CmJwNDlRQTUzYXE3T1FqcGlPRDR0
            ZjEwdHI0c0pJY25JR2s0cEhFcnc0N1EKLS0tIFJoM3dPYlpFV3RkUlJobDhPenJQ
            SUs5UGtDRGluRW9oMmlKYzRRY2U4NW8KooW9vqT7T8aoC+hF/rw1+NykoaHb2y50
            9sYKW9RxL6KE4ypYXH8oArAv1FkhJov0OddE+ruJRffbQIJyr58mOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T16:56:54Z"
    mac: ENC[AES256_GCM,data:oK1KR+brjmNLSxVraVh6tLIzUzjsQKJhQRj4HS+eRn1z3peJ61u3DLVft/IQm1AXGFCAYdzsKdNa+TmuxUJT1xKqhbPfz89x3qBSbuYuCs8f2p8tCqbZMem1EpZnGURU78UzLiGQK3tDxHjH3rfv0tGWAJOeISTap6/fcml42cQ=,iv:rjGzevRf2BQonolIzNyWXj5sS+sRgxndr5vQHm2ofBI=,tag:lx/eOrYIQL7WWHyFWtSWUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
