apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:DB3SkvBEBfct3y43gO+FDIKIdI+26ohwpBhwVCffNrjwvG3Pe0yusQ==,iv:FpGstkqB1j6kvmauU/uJ6IBWQ9cPxPjhd+BInaQ//IY=,tag:YSNdlAMLHw390aGqIJX3NA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4L2htOUl1R3d6R3JGN3BR
            cmQvY3FoS1Z1UEU3QmhPM3VkMGkxMW5SZEZ3CklYa3hDZ2pZeDNRVWd2T3Z4L2xE
            Qm9ldkV3bWltZmY2Ujh0Z0F6R1RTeWsKLS0tIHJYeXArVHFqelpVK1JZdzdaRWRq
            Q2k4eTViVVV4dFREMXBqcmdtSTlnVHcKZqx0+7RBKYGTF9VkpN7nobSkcWWuB3Jo
            Ws3kkmep9L8nqZk1lATu9QixxlxT+b27xThivC7gflydfOUvcVzKrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T14:54:58Z"
    mac: ENC[AES256_GCM,data:uEgH9jfp6IXmhbMTdRQkBO82c62uuRqsjjgvz3lf4odJSDKxipVZz0cP80Q0//x2AC/R4piAVoez5W4EhRJ+Lr1UQ5IKofNwWRLQ0ueN1O+BTxoXr/RRHGjMi8j61NeFuBLaXY9P/KBs0u/nC6UeP0MvQmZjsqcejQcCD9Flcf8=,iv:jp0MfgAO5HhVrLznqEqVtwu6UOYuXPQYHo5RS24WvIs=,tag:1LE8gmQLWYOkoOVxnNov1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
