apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:f4HpGcRMMO3/AH/j8Yo=,iv:fWc7VT+6yiwCTKSpldZ7FPIwWkHw8g+kQ5j1pqUUTwE=,tag:U7ZixrXCjQ+6ibzy+g+5RA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:l6pMCrgTc7k1FInZBCRtetOf,iv:gjDVzNq9edbUrxWvHhbKD2nblOGbqXQYX0FUNwar1Ac=,tag:LIVvcSCDTAFha8PwIO3YmQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:JLrlnzGjLNcsRpoWQDq3q90XyfcLQ5nwMV9AkyWf54ylISbQ,iv:u2udr/8f+O5iCTjD+WFiWgRPxtX5lMyo9WWQAUqWWNE=,tag:3cq0cP5qKRviJ1xqi2yqog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeXhybCtQKzhlUHI5cWlX
            bElDY2wrOWFOU0lsekk3REJlbWJoenE4ZEFRClBVTzdJcXZBb09zNHE0U21iaFJ2
            L0Z5Y091emsrUE52cW5YK2QvaG9RdVUKLS0tIEJCNU5GOHU4RUVMNzEwTEo5R2I3
            TVJlb1lnSFNWSjZRWHR6RVJnMi9RNzQKbzHN33eAJuXfyXmutZ5MDSiAOqvMEZiw
            Qk9b6LEcRXPF7bGzXCtL6DXBZh/wDfXV08DskMMl73SQIyhohuN6Eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T17:01:09Z"
    mac: ENC[AES256_GCM,data:Bnvrpdg2mIwmfl7Wjdm58PmhzUn67mPDCEbsusxzrUWVQdg5rnvwJaRImAIqS/DbeVfxR80+AEuGhZO0h6xuL3ibmk2T/CY0dOOP1G8HYEItBsHZBAMoWHF76/ziZSb5c4KePevTrBF5Zn3bygUOOEiJwA9yaNCsvcSLKDQEYFI=,iv:m0ZgOOiJhXSeRRex1vHIGXBdWYNc4JZyI8YqfoR2iCk=,tag:QCWj9UKvrwmKH9WaNj5j5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
