apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:wOaEvPoCjNrD4l7osf8=,iv:TH+hgJyhLPe8J49BgLn+MvxQFK3r1NUxvUKMh4q6xw4=,tag:waZGLqv89qyES3nqBA9w0A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/dDbj6sBz7VUGA3qwDeIkg6x,iv:LYMgwnao8XS15Ghp3JcJTcF5H1v9K+oC+HhFyUazDGE=,tag:B3O3ynvKBlPrPQEEWJMENg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ez1Vldrja/YSEGDcw2aYtGsa5wy5AP/H6zyWbVHsUfPUQz94,iv:rxNAwffL7EYUarpSSMhSwk3qeM9F4Z7SDmvTarHwJoM=,tag:DThA3llqZSHGXqr2UsTsQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aktKeW4zLzgwdGhsUHVy
            amg1Y09hL3J1VmgrK2xUL3hyZGRBSVpqWm04Cm1BU1hOYVVmTlZUU3hEUEFROUh5
            ZC9qczdEdG5KMHBnSlVNaFRjbXBGTGsKLS0tIEVmbzFPTlZzY25SVVZxZnBxaURF
            MVFkZ3VPVVg3SEsvdDNHS3lTNHEyQlUKBGgrFhH0IJnrjwYyBDGSmraRqczDbYrY
            aLAE1JXUvbH4mmM/QlU0TEiMz05Lo9DyDIMOfm94t3xdJvVSbuLQTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T17:40:58Z"
    mac: ENC[AES256_GCM,data:1cyeYi2VpoaxEIOgiIqLymfFL69Llz7bwDfT3gyLr3S/wDxXZLi7LjZYAKI7EQjocBm/p1MPTWM3AR2OjUEhUuKx+RHHGXd/EtnftEyJLAnbNNwJ4cyejhoXgLVKFewa5MdBGQCFGNUYPUi4Eplgqt6+e7cWZB8L0F1pgsuxRas=,iv:Itgh4SJUrWup6iQQCX0uyr1h/GJw9GJkD8H/jxNLGNQ=,tag:YVR76oORvlxtJUkyUO0YNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
