apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:oj4ytohkc2t2Px59IrastLQkfz+MjSwvnUIzg0PTbvRj1V8154k6RA==,iv:J+kkq5rpTBrgcD2BZAR2WcMrSF97YOJTUqndsBjkxEU=,tag:JXWbFelrhodnV3oMrsNyDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwR056WjV6RWZWdHVmR2dN
            YzlPZXlySitkR25McFdFVTBBbjFiamJQM0ZzCjJjbGZZcWxBcGNLZjdhQ0l0cjlW
            bk04bnhmazd3dXZjbHBUZnA3RzdoTjAKLS0tIDMvZG1yTmNNeUV4ZDhOcTFHb0Vj
            TTFLMlBXVWh2R3ZwRzVLZWF1MFFsVG8K2iHtg6AoiGHp2KwB4cJfE2ZWJXBVh5Rk
            q/jwRJecuEt0vqOu1YhjTMYKEJhFgAc279mzr2phg0ORJQ3d4aXPug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T16:56:53Z"
    mac: ENC[AES256_GCM,data:C3oAY8Qdrf2JFclbTdHSvpfwgkBE4LtCat0DyS0Eh9J+pW2M6yGmTb2BSOW1g9E6nwyjhex6qbk8x/VqzWOfjVHsXO5ed4n59SNvl5smySDf/zSfu65WftRalB/gHRcAIuII0jBmPC5KvnIXt/zFZFqQQw3FQo3UeWv46gXB0Us=,iv:E8hNJ1veKgHJ+9fGuinHcCUfv/KD6Rc6XUHjG1g9BaI=,tag:G4FpRjjO8bDYl9lpTYHGVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
