apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:j3iXV03R3ub9XpsNkNCUqwF+hSzCB6y1yX6EgESWetnq0HzVKseb3A==,iv:7aqEnUR/1ReG6d1jS+VqikpY2M9upuYzxmKY5PvHznY=,tag:5stOvhRZ1iUvoJ2mN33Z/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWODNUMXJMUjZodnhZbzJT
            YWtHbXl0NTN6Qit4bUlNMGpyR0Q1bkdiMTJrCmVHRnNpQ21KWUJIeWdpbTNNbW9x
            R3dla0JueDlLYkM5T1FEMzFjSC8xYzQKLS0tIHdOU1Qvam1KZHh6QlU0NzBINys3
            amx2TXRvcjFEZlJBOHBzNS80cEIwZlEK7miKH/wOPjR6Bzoeyil5owdHlL1tNKnC
            Zxhr7opUwBHplZ6UkA1Nl32N9sfmcIsTNTgwsAyWM+4izANC7t82zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T17:01:09Z"
    mac: ENC[AES256_GCM,data:QvBazzTWEUunX8S9bklU72Z9PHU5euwNEVFrANVirMmYmYDJBjHBhIozs+fSC1aKfstfG2GY06W/F3jBYP+yZzCzk4jzKnFXg4l/Fe2fjFJofDfXEUsetf97sTqLDfJB0ZoFPpzxFJ6c0ScXkdm0gneuuh1/Lo9XIhbYuJjm3Oo=,iv:zxNWo1efH23EKwkKEUyxAvPCJaQ5O5ZyH+8VlX0bgvQ=,tag:/pvWKLsip8MVV7XLY04NNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
