apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:1VosCqOe9h17jkU1RpGRakkObiimESK2HLphw705FMeYtttXj9HYfQ==,iv:YWiELM0ua/KUEB6sLFf/opZz/5F6gishuTTi30LkNGE=,tag:FaQ2VkM81gbF17gkOXQXsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamxHVEZjWHRIckttd2xw
            VmJZM0ZSRExINVoxYStTZmN5ck9EUnR2S244CkNkbHJHdVlVczJzdXBRVXFCN0Za
            ZTF3RWVTSFZLVzB5SXVtakI5cHZPdmsKLS0tIDJDbTh4NDdMVDdTTC9OUXpOZlF5
            cG40Wm9pTU1pbTcvelN1NFJIbkR4bjQK3EXoqTyqDFjdNAYXC0bFOX+kARBDxna3
            BzXqj1osL7VSU58l9jFpfS4pnu2Kxdbemb5JjSyAv9V4RSFpyARZxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T14:22:35Z"
    mac: ENC[AES256_GCM,data:SsgP8rgyNrG0s7wb4ZA7Xd63gE69Ghuow5hC2S6OwGdRe83Sr8VWqOrdgQeAIhV26Hxz/y2LDOHxmzESYq+fA7UTyjY0KP2vJ282UR6lcEywrb4H28CCR54sbvXMI6mrvuKbPvpoFgb2A9jRbSJlubaZ6CB3Pev6eCFwd8aGAJ0=,iv:5thnUmGKGtbHuWxrtwQnovwTDu9tWWR6aVdTUKW7cTU=,tag:5PqZyrLyFl/mA37xlWX5rQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
