apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:OJohh2cFk726aiUlhmH+SlBKHKdxJ7G+jC/Ug7QmU4aMnOfIxO6YbA==,iv:/86tZEBCFUmhT3BiLSuZ6YzgBqEE25+1DprBpUa1ZXA=,tag:f3YWkW8RdJ/eFjUJibh82Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeEhybWRhZjN6Q0hvbFZz
            YkpzcENiM2JNMHdUSVc5OUZhU0xEckNleUFZCnI3Wm41NWNlY3plQk91em55b1ZT
            TldDczVuOElueTBWN3p1TThQOHIvRDQKLS0tICtXdWQyaFRYQTV2aUEzNjdhVjhv
            ZEFobEwvYU83YnRnSmFWRFlWeElsOVEKxn4xq6YY2ogcLjFRo7HgvC+dflnbhe9u
            qvrg8HibzzBfc57kZ65Oe+SNaLIj39NmoTaUzUNuUgxtfMRf+el5kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T22:12:14Z"
    mac: ENC[AES256_GCM,data:fwcE4O52PKxaLWPJnq27FGYNooUvjFn8afAptfdwHZ3Nh9mXAkk8ZrvQKtEPWoQuBjwj9MMMe4CnY2ADEj/yyRQ2t/my+OS3tWPfKInZ42yXmS+wUvwXMc859BuscxQaSbo3YgiP//MbQS4eNcWMA+9M4mTVMCxSjreXTD9zlAs=,iv:zjvYapyYpMwslEvgPu1M96PXLooQ7hwoxi+7TEsnzUs=,tag:BQ9hcoRohDuEHARrXn8Ajg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
