apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:1SkQXDCoUHHYup5xEokKBpqqVaZt7Aco3IAAyU+SP8RMQskgVS29+g==,iv:/TPzuv3O8NKQxSQm7gzRH4+o3vaNBIDl+1Mp42Hs9ns=,tag:BQ5BcriDaL4h8Ld/amjKgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7s209sdwelu88sh788kk7wgu68fgec03js7taasrz27346uhqxslr7nwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTjVLYlhKandnUTRxYUFW
            WUpjdkdrSmFQb1VlaWIrOGZEN0dJa0RzNlg4CmM0QlFKaE1jc2JJMmlmUHNGYU14
            K3RxMno2dEtHVDY1cEd6bnR2Z3grSkEKLS0tIHFFT1RJdS9ZWUFzdVhreFZDNFhl
            WXM2NWo5T2pUdHdqcHp0dm1uaDZBVkUKFV+IP+JCzjYe85Iam1JgVlK2qmMf4yNy
            DFFqiFq5jTqyGBgpc7Cd7W9n8HKSdy+T9mSP/UWZi5FAB+j8xSgAnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T23:20:44Z"
    mac: ENC[AES256_GCM,data:ijUM7MbA4665wshESFKww9/SGoLwF64iEzSDmv1EcJ93cg5us5O2ZbcaZB09AUM9clGmES0OZ5AAf+HrCRbRu8LoYDNYj2mvTMv92dLq50HzAhqb64mKngQqIH9q5axuUnyUFgNa1fewdP8m05cp7xM2CMl/t/ZJnoUgOjLW7qA=,iv:HXMIZpBgKiNvIhtLMewnpftcRZUXEm2DLHQc+SyKs+4=,tag:MonDdUcTTjZonQq0ZIS6ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
